Добавил 1-е ИЗ, вариант 7(rundId 403)
Xatabch/technopark_cpp pull request #1
Opened 2018-10-07 17:05 UTC by Xatabch

Индивидуально задание №1

2018-10-07 21:15 UTC, leshiy1295 requested changes
Необходимо поправить замечания - в некоторых местах не дублировал комментарии - по каждой из ошибок нужно поправить везде в аналогичных местах
После внесения правок нужно прогнать ещё раз в АСТС и оставить в Pull Request runId успешной попытки

2018-10-07 21:15 UTC, leshiy1295 commented on main.c
> +    printf("stack >");
ничего дополнительно выводить в задаче не нужно
отладочную печать можно прятать за специальный define-флаг, который можно указывать при сборке приложения

2018-10-07 21:15 UTC, leshiy1295 commented on main.c
> +        return -5;
магические константы недопустимы

2018-10-07 21:15 UTC, leshiy1295 commented on main.c
> +    Node *out;
все переменные нужно явно инициализировать при определении

2018-10-07 21:15 UTC, leshiy1295 commented on main.c
> +            if((*matrix)[0] != NULL)
рекомендуется везде без исключения ставить фигурные скобки для того, чтобы избежать глупых ошибок в будущем

2018-10-07 21:15 UTC, leshiy1295 commented on main.c
> +                error = ALLOCATE_MEMORY_ERROR;
в этом случае разве не нужно освободить память под tmp и другие указатели и завершить выполнение функции?

2018-10-07 21:15 UTC, leshiy1295 commented on main.c
> +        (void) pop(&*s);
зачем тут (void) ?

2018-10-07 21:15 UTC, leshiy1295 commented on main.c
> +        if(isBalance(data[i]))
в C sneak_case является более предпочтительным, чем camelCase

2018-10-07 21:15 UTC, leshiy1295 commented on main.c
> +            error = addRow(&(*matrix), buffer, *n);
зачем нужно делать &(*) ?

2018-10-07 21:15 UTC, leshiy1295 commented on main.c
> +    char *buffer = malloc(1000 * sizeof(char));
магическая константа

2018-10-07 21:15 UTC, leshiy1295 commented on main.c
> +    int ch, i = 0;
не стоит определять несколько переменных сразу на одной строке

2018-10-07 21:15 UTC, leshiy1295 commented on main.c
> +    if((*matrix) == NULL)
а что если matrix == NULL?

2018-10-07 21:15 UTC, leshiy1295 commented on main.c
> +    Node *head = NULL;
что если string == NULL?

2018-10-07 21:15 UTC, leshiy1295 commented on main.c
> +
нужно проверять валидность входных данных

2018-10-07 21:15 UTC, leshiy1295 commented on main.c
> +    error = readLine(buffer, &matrix, &n);
функцию main можно разбить на отдельные подфункции:
- ввода и инициализации данных
- обработки
- вывода и освобождения ресурсов
Также программу стоит оформить в следующем порядке
- интерфейс - описание всех используемых функций
- определение main
- реализация - определение всех используемых функций

2018-10-07 21:15 UTC, leshiy1295 commented on main.c
> +                return 0;
лучше использовать bool, а не int

2018-10-07 21:15 UTC, leshiy1295 commented on main.c
> +int isBalance(char *string) {
неудачно сформулировано название функции

2018-10-08 06:48 UTC, Xatabch commented on main.c
> +                error = ALLOCATE_MEMORY_ERROR;
Данная ошибка у меня протаскивается как бы к самому верху как в структурном подходе программирования, и уже если при выводе что-то обнаружилось, то вывод не происходит, и все очищается

2018-10-08 07:07 UTC, Xatabch commented
Код готов к повторному ревью( runId 1468)

2018-10-08 13:12 UTC, leshiy1295 requested changes

2018-10-08 13:12 UTC, leshiy1295 commented on main.c
> +    if(string != NULL)
таким способом вы искусственно создаёте себе лишний отступ
контракты обычно проверяют if (!ok) { return }

2018-10-08 13:12 UTC, leshiy1295 commented on main.c
> +                error = ALLOCATE_MEMORY_ERROR;
в том-то и дело, что она не особо правильно протаскивается
если у Вас один раз произошёл error - например, из-за нехватки памяти, то он и в следующий раз произойдёт, тем самым значение error затрётся следующим
нужно при первом же появлении error прекращать работу (можно и структурно, особенно если это произошло в цикле, то обязательно структурно) и освобождать память

2018-10-08 13:38 UTC, Xatabch commented
Код готов к ревью(runId 1515)

2018-10-11 21:44 UTC, merged

2018-10-15 11:02 UTC, leshiy1295 commented on main.c
> +        printf("[error]");
семантически более правильно возвращать ошибку и давать возможность пользователю уже что-то выводить
в реальных системах допускается логирование в специальном формате, разрешённом для конкретной сущности

2018-10-15 11:02 UTC, leshiy1295 commented on main.c
> +    if(tmp != NULL) {
обычно проще сначала обработать "плохой" случай и выйти из функции
зато потом можно без отступа писать основное содержание

2018-10-15 11:02 UTC, leshiy1295 commented on main.c
> +        tmp->next = *head;
что если будет передан head == NULL?

2018-10-15 11:02 UTC, leshiy1295 commented on main.c
> +    Node *out = *head;
что будет, если передать head == NULL?

2018-10-15 11:02 UTC, leshiy1295 commented on main.c
> +void free_matrix(char **data, size_t n)
по возможности стоит указывать, какие параметры являются const

2018-10-15 11:02 UTC, leshiy1295 commented on main.c
> +        (*matrix) = calloc(1, sizeof(char*));
семантически правильнее сначала менять локальные переменные - потом только в случае успеха присваивать результат выходной переменной

2018-10-15 11:02 UTC, leshiy1295 commented on main.c
> +                    free_matrix((*matrix), (n-1));
очень много копипасты с free...

2018-10-15 11:02 UTC, leshiy1295 commented on main.c
> +        res = is_empty(head);
что-то не так с отступами

2018-10-15 11:02 UTC, leshiy1295 commented on main.c
> +
валидность так и не проверяется

2018-10-15 11:02 UTC, leshiy1295 commented on main.c
> +    while((ch = getc(stdin)))
getc возвращает int, а не char

2018-10-15 11:02 UTC, leshiy1295 commented on main.c
> +    char *buffer = malloc(START_ARRAY_SIZE * sizeof(char));
что если malloc упал?